### ISSUE TITLE
[5pt] Group tasks

### ISSUE THREAD

**Issue by SimonGideon** [SimonGideon/Catalog-of-my-things#1]
- Create an Item class in a separate .rb file.
- All Item class properties visible in the diagram should be defined and set up in the constructor method. Exception: properties for the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
- Add all methods visible in the diagram.
- Implement methods:
can_be_archived?() in the Item class
should return true if published_date is older than 10 years
otherwise, it should return false
move_to_archive() in the Item class
should reuse can_be_archived?() method
should change the archived property to true if the result of the can_be_archived?() method is true
should do nothing if the result of the can_be_archived?() method is false
- Create a main.rb file that will serve as your console app entry-point.
- Implement startup actions:
- Present the user with a list of options to perform.
Let users choose an option.
If needed, ask for parameters for the option.
Have a way to quit the app.

**Comment by rloterh** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your description has the following info:
* link to their GitHub project
* information about the number of people in their group
* list of GitHub usernames assigned to: `Team member #1`, `Team member #2`, `Team member #3` etc.

Kindly also ensure that your board is based on [this template board](https://github.com/microverseinc/curriculum-ruby/projects/1)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
